### ISSUE TITLE
node:8.2.1   SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by Here21** [Molunerfinn/vue-koa-demo#14]
`npm start dev` is ok, but when I run `node app.js`, I got these:
```js
▶ node app.js 
/Users/simon/workspace/studyCode/node/vue-koa-demo/app.js:1
(function (exports, require, module, __filename, __dirname) { import Koa from 'koa';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

I use nvm to install node@8.2.1, I saw koa2 need version 7.6+.

**Comment by Molunerfinn** [comment]
Use `npm run server` instead
