### ISSUE TITLE
下载项目安装依赖后node app.js报错

### ISSUE THREAD

**Issue by kaixinhlz** [Molunerfinn/vue-koa-demo#6]
报错内容：
D:\study\koa-node0519\vue-koa-demo-master\app.js:18
app.use(async function(ctx, next){
        ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by Molunerfinn** [comment]
你的Node的版本是多少？

**Comment by Molunerfinn** [comment]
这个问题应该是你Node版本低于7.6的问题。可以留意Readme里的提示，请更新Node的版本~
